spring:
  datasource:
    url: jdbc:log4jdbc:h2:~/testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    passsword:
  h2.console:
    enabled: true
  sql.init:
    mode: always
    schema-locations:
      - classpath:/ddl.sql
    data-locations:
      - classpath:/dml.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    