spring:
  datasource:
#    url: jdbc:h2:~/testdb
#    driver-class-name: org.h2.Driver
    url: jdbc:log4jdbc:h2:~/testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  h2.console: #http://localhost:8080/h2-console
    enabled: true
  sql.init:
    mode: always
    schema-locations:
      - classpath:/ddl.sql
    data-locations:
      - classpath:/dml.sql
